### ISSUE TITLE
some annotations are missing

### ISSUE THREAD

**Issue by UejnYaM** [stresearch/otw#3]
use homes dataset [0:406] for training, but only 383 video have annotations.  For example, #16 is missing

**Comment by UejnYaM** [comment]
mising files are [16, 19, 21, 30, 40, 52, 63, 66, 67, 83, 96, 168, 214, 227, 262, 289, 377, 403, 440, 510, 540, 565]

**Comment by jebyrne** [comment]
Errata

   - An unlabeled subset of these videos are created by holding the camera
   by hand rather than leaning it against the window, which results in
   unstabilized video
   - Mounting and Dismounting bike class typically also includes when a
   bike is being walked
   - Videos are not exhaustively labeled, such that there exist videos
   where an activity class occurs (e.g. entering) where the activity is not
   labeled.
   - Videos 16, 19, 21, 30, 40, 52, 63, 66, 67, 83, 96, 168, 214, 227, 262,
   289, 377, 403, 440, 510, 540, 565 and 600 are withheld because of issues
   with video frame rate or tracking. The rest of the videos should have
   limited tracking errors.
